import { performance } from "perf_hooks";

const LOGS_URL = "http://localhost:8080/logs";

const TOTAL_LOGS_TO_SEND = 1_000_000;
const BATCH_SIZE = 2_000;
const CONCURRENT_REQUESTS = 1;

const AGGREGATION_INTERVAL_MS = 1_000;

// We create a fixed time range for this test.
// All generated logs will fall inside this range.
const TEST_START = new Date();
TEST_START.setSeconds(0, 0);

const TEST_END = new Date(
  TEST_START.getTime() + 60 * 60 * 1000
);

const AGGREGATE_URL =
  `http://localhost:8080/logs/aggregate` +
  `?since=${encodeURIComponent(TEST_START.toISOString())}` +
  `&until=${encodeURIComponent(TEST_END.toISOString())}` +
  `&bucket=1m`;

interface LogEntry {
  timestamp: string;
  level: "debug" | "info" | "warn" | "error";
  service: string;
  message: string;
  attributes: Record<string, string | number | boolean>;
}

interface BatchResult {
  success: boolean;
  size: number;
}

interface AggregationResult {
  latency: number;
  status: number;
}

function generateBatch(
  size: number,
  batchOffset: number
): { logs: LogEntry[] } {
  const levels: LogEntry["level"][] = [
    "debug",
    "info",
    "warn",
    "error",
  ];

  const services = [
    "checkout",
    "auth",
    "payment",
    "inventory",
  ];

  const logs: LogEntry[] = [];

  for (let i = 0; i < size; i++) {
    /*
     * Spread timestamps across the one-hour test range.
     * This makes aggregation actually process the logs
     * generated by this test.
     */
    const globalIndex = batchOffset + i;

    const timestampOffset =
      Math.floor(
        (globalIndex / TOTAL_LOGS_TO_SEND) *
          (TEST_END.getTime() - TEST_START.getTime())
      );

    const timestamp = new Date(
      TEST_START.getTime() + timestampOffset
    ).toISOString();

    logs.push({
      timestamp,

      level:
        levels[
          Math.floor(Math.random() * levels.length)
        ],

      service:
        services[
          Math.floor(Math.random() * services.length)
        ],

      message:
        `Test log message number ${globalIndex}`,

      attributes: {
        user_id: String(
          Math.floor(Math.random() * 10000)
        ),
        region: "eu-west",
        retries: Math.floor(
          Math.random() * 5
        ),
      },
    });
  }

  return { logs };
}

async function sendBatch(
  batch: { logs: LogEntry[] }
): Promise<boolean> {
  try {
    const response = await fetch(LOGS_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(batch),
    });

    return response.ok;
  } catch {
    return false;
  }
}

async function runIngestion(): Promise<{
  successfulLogs: number;
  failedBatches: number;
  durationMs: number;
}> {
  const totalBatches = Math.ceil(
    TOTAL_LOGS_TO_SEND / BATCH_SIZE
  );

  let successfulLogs = 0;
  let failedBatches = 0;

  const ingestionStart = performance.now();

  for (
    let i = 0;
    i < totalBatches;
    i += CONCURRENT_REQUESTS
  ) {
    const promises: Promise<BatchResult>[] = [];

    for (
      let j = 0;
      j < CONCURRENT_REQUESTS &&
      i + j < totalBatches;
      j++
    ) {
      const batchIndex = i + j;

      const currentBatchSize = Math.min(
        BATCH_SIZE,
        TOTAL_LOGS_TO_SEND -
          batchIndex * BATCH_SIZE
      );

      const batchOffset =
        batchIndex * BATCH_SIZE;

      const batch = generateBatch(
        currentBatchSize,
        batchOffset
      );

      promises.push(
        sendBatch(batch).then((success) => ({
          success,
          size: currentBatchSize,
        }))
      );
    }

    const results = await Promise.all(
      promises
    );

    for (const result of results) {
      if (result.success) {
        successfulLogs += result.size;
      } else {
        failedBatches++;
      }
    }

    process.stdout.write(
      `\rIngestion: ${successfulLogs.toLocaleString()}/${TOTAL_LOGS_TO_SEND.toLocaleString()}`
    );
  }

  const durationMs =
    performance.now() - ingestionStart;

  console.log(
    `\nIngestion finished. Failed batches: ${failedBatches}`
  );

  return {
    successfulLogs,
    failedBatches,
    durationMs,
  };
}

async function runAggregationMonitor(
  stopSignal: {
    stopped: boolean;
  }
): Promise<{
  results: AggregationResult[];
  startedAt: number;
  finishedAt: number;
}> {
  const results: AggregationResult[] = [];

  const startedAt = performance.now();

  while (!stopSignal.stopped) {
    const requestStart =
      performance.now();

    try {
      const response = await fetch(
        AGGREGATE_URL
      );

      const latency =
        performance.now() -
        requestStart;

      if (response.ok) {
        results.push({
          latency,
          status: response.status,
        });
      } else {
        console.log(
          `\nAggregation failed: HTTP ${response.status}`
        );
      }
    } catch {
      console.log(
        "\nAggregation request failed."
      );
    }

    const elapsed =
      performance.now() -
      requestStart;

    const waitTime = Math.max(
      0,
      AGGREGATION_INTERVAL_MS -
        elapsed
    );

    if (!stopSignal.stopped) {
      await new Promise<void>((resolve) =>
        setTimeout(
          resolve,
          waitTime
        )
      );
    }
  }

  return {
    results,
    startedAt,
    finishedAt: performance.now(),
  };
}

function percentile(
  values: number[],
  percentileValue: number
): number {
  if (values.length === 0) {
    return 0;
  }

  const sorted = [...values].sort(
    (a, b) => a - b
  );

  const index = Math.ceil(
    (percentileValue / 100) *
      sorted.length
  ) - 1;

  return sorted[
    Math.max(0, index)
  ];
}

function printAggregationResults(
  results: AggregationResult[]
): void {
  console.log(
    "\n\n--- Aggregation Results ---"
  );

  console.log(
    `Requests: ${results.length}`
  );

  if (results.length === 0) {
    console.log(
      "No successful aggregation requests."
    );

    return;
  }

  const latencies = results.map(
    (result) => result.latency
  );

  const average =
    latencies.reduce(
      (sum, value) =>
        sum + value,
      0
    ) / latencies.length;

  console.log(
    `Min:  ${Math.min(...latencies).toFixed(2)} ms`
  );

  console.log(
    `Avg:  ${average.toFixed(2)} ms`
  );

  console.log(
    `P50:  ${percentile(
      latencies,
      50
    ).toFixed(2)} ms`
  );

  console.log(
    `P95:  ${percentile(
      latencies,
      95
    ).toFixed(2)} ms`
  );

  console.log(
    `P99:  ${percentile(
      latencies,
      99
    ).toFixed(2)} ms`
  );

  console.log(
    `Max:  ${Math.max(...latencies).toFixed(2)} ms`
  );
}

async function main(): Promise<void> {
  console.log(
    "\nStarting ingestion + aggregation stress test..."
  );

  console.log(
    `Ingestion: ${TOTAL_LOGS_TO_SEND.toLocaleString()} logs`
  );

  console.log(
    `Batch Size: ${BATCH_SIZE}`
  );

  console.log(
    `Concurrency: ${CONCURRENT_REQUESTS}`
  );

  console.log(
    `Aggregation: ~1 request/second`
  );

  console.log(
    `Aggregation range:`
  );

  console.log(
    `  ${TEST_START.toISOString()}`
  );

  console.log(
    `  ${TEST_END.toISOString()}`
  );

  console.log(
    `Bucket: 1m`
  );

  console.log(
    `\nAggregation URL:`
  );

  console.log(
    AGGREGATE_URL
  );

  const stopSignal = {
    stopped: false,
  };

  /*
   * Start aggregation first.
   *
   * This is intentional:
   * aggregation runs while ingestion is happening,
   * matching the project requirement.
   */
  const aggregationPromise =
    runAggregationMonitor(
      stopSignal
    );

  const ingestionPromise =
    runIngestion();

  const ingestionResult =
    await ingestionPromise;

  /*
   * Give the aggregation monitor a small chance
   * to observe the final state after ingestion.
   */
  await new Promise<void>((resolve) =>
    setTimeout(resolve, 1_000)
  );

  stopSignal.stopped = true;

  const aggregationResult =
    await aggregationPromise;

  /*
   * ----------------------------------------
   * Final results
   * ----------------------------------------
   */

  console.log(
    "\n\n========================================"
  );

  console.log(
    "FINAL TEST RESULTS"
  );

  console.log(
    "========================================"
  );

  console.log(
    `Successful logs: ${ingestionResult.successfulLogs.toLocaleString()}`
  );

  console.log(
    `Failed batches: ${ingestionResult.failedBatches}`
  );

  const ingestionSeconds =
    ingestionResult.durationMs /
    1000;

  const ingestionThroughput =
    ingestionResult.successfulLogs /
    ingestionSeconds;

  console.log(
    `Ingestion time: ${ingestionSeconds.toFixed(2)} seconds`
  );

  console.log(
    `Ingestion throughput: ${ingestionThroughput.toFixed(2)} logs/sec`
  );

  console.log(
    `Aggregation requests: ${aggregationResult.results.length}`
  );

  printAggregationResults(
    aggregationResult.results
  );

  console.log(
    "\n========================================"
  );
}

main().catch((error) => {
  console.error(
    "\nTest failed:",
    error
  );

  process.exit(1);
});